### ISSUE TITLE
No such file or directory: 'D:\\yolov4-pytorch-master/VOCdevkit/VOC2007/JPEGImages/52-1-P2-F21-F1.jpg'

### ISSUE THREAD

**Issue by LiYing-hub-coder** [bubbliiiing/yolov4-pytorch#206]
请问为什么跑train.py的时候会报这个错啊，应该是解析文件路径有问题，但是没有找到解析文件路径的代码

**Comment by LiYing-hub-coder** [comment]
之前那个错解决了，是文件路径的问题，我修改了一下vc_annotations.py，但是现在又报一个别的错：
AssertionError: Torch not compiled with CUDA enabled
但是我用python：
import torch
print(torch.__version__)
print(torch.cuda.is_available())
最后输出的结果为TRUE，1.9.0+cu102(我的cuda下的是10.2版本的），
求问好心人这是为什么

**Comment by bubbliiiing** [comment]
emm这个算错误吗？
