### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by feixiangdekaka** [bubbliiiing/yolov4-pytorch#21]
请问会更新test.py 吗  然后生成计算map所需的txt

**Comment by bubbliiiing** [comment]
你猜有没有……

**Comment by zzl777** [comment]
我觉得可以有！！！

**Comment by bubbliiiing** [comment]
不是有嘛/。。

**Comment by mowushuang** [comment]
请问我运行test.py后，出现RuntimeError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 5.80 GiB total capacity; 528.20 MiB already allocated; 18.00 MiB free; 27.80 MiB cached)，是要在test.py中加入mode.eval()函数和使用with torch.no_grad()么？

**Comment by bubbliiiing** [comment]
test.py不是用来看网络结构的吗

**Comment by mowushuang** [comment]
对，看cspdarknet53的，我运行test.py后，出现RuntimeError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 5.80 GiB total capacity; 528.20 MiB already allocated; 18.00 MiB free; 27.80 MiB cached)，那应该怎么解决了
